#[compute]
#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set=0,binding=0) uniform sampler2D current_color; layout(set=0,binding=1) uniform sampler2D current_depth;
layout(set=0,binding=2) uniform sampler2D history_color; layout(set=0,binding=3) uniform sampler2D history_depth;
layout(set=0,binding=4,rgba16f) uniform image2D reflection_output; layout(set=0,binding=5,rgba16f) uniform image2D history_color_output; layout(set=0,binding=6,r16f) uniform image2D history_depth_output;
layout(set=0,binding=7,std140) uniform TemporalParams { mat4 current_inverse_view_projection; mat4 previous_view_projection; vec4 destination_size; vec4 temporal_settings; vec4 ocean_level; } params;
vec2 previous_uv(vec2 uv, out bool valid) { vec2 ndc=uv*2.0-1.0; vec4 a=params.current_inverse_view_projection*vec4(ndc,0.0,1.0); vec4 b=params.current_inverse_view_projection*vec4(ndc,1.0,1.0); if(abs(a.w)<=0.000001||abs(b.w)<=0.000001){valid=false;return vec2(0.0);} a/=a.w;b/=b.w;float d=b.y-a.y;if(abs(d)<=0.000001){valid=false;return vec2(0.0);}float t=(params.ocean_level.x-a.y)/d;if(t<0.0||t>1.0){valid=false;return vec2(0.0);}vec4 previous=params.previous_view_projection*vec4(mix(a.xyz,b.xyz,t),1.0);if(previous.w<=0.000001){valid=false;return vec2(0.0);}vec2 result=previous.xy/previous.w*0.5+0.5;valid=all(greaterThanEqual(result,vec2(0.0)))&&all(lessThanEqual(result,vec2(1.0)));return result; }
void main(){ivec2 pixel=ivec2(gl_GlobalInvocationID.xy);ivec2 extent=ivec2(params.destination_size.xy);if(any(greaterThanEqual(pixel,extent)))return;vec4 current=texelFetch(current_color,pixel,0);float current_depth_value=texelFetch(current_depth,pixel,0).r;bool current_valid=current.a>0.001&&current_depth_value>0.000001;vec4 result=current;bool valid=false;vec2 uv=(vec2(pixel)+0.5)/params.destination_size.xy;vec2 old_uv=previous_uv(uv,valid);if(params.temporal_settings.x>0.5&&params.temporal_settings.w>0.5&&valid&&current_valid){vec4 history=texture(history_color,old_uv);float old_depth=texture(history_depth,old_uv).r;float confidence=1.0-smoothstep(params.temporal_settings.z,params.temporal_settings.z*2.0,abs(current_depth_value-old_depth));if(history.a>0.001&&old_depth>0.000001&&confidence>0.0){float weight=clamp(params.temporal_settings.y*confidence*min(current.a,history.a),0.0,1.0);result.rgb=mix(current.rgb,history.rgb,weight);}}if(!current_valid)result=vec4(0.0);imageStore(reflection_output,pixel,result);imageStore(history_color_output,pixel,result);imageStore(history_depth_output,pixel,vec4(current_valid?current_depth_value:0.0));}
